import {StyleSheet, Platform, StatusBar} from 'react-native';
import colors from '../../assets/colors/colors.js';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.aratuBeige,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  topNavbar: {
    position: 'absolute',
    width: '100%',
    height: 52,
    top: 0,
    backgroundColor: colors.aratuDarkBeige,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    zIndex: 5000,
  },
  arrowIcon: {
    width: 20,
    height: 20,
  },
  gearIcon: {
    width: 20,
    height: 20,
  },
  logo: {
    fontFamily: 'Gazebo',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 20,
    lineHeight: 24,
    color: '#000000',
  },
  profileRectangle: {
    position: 'relative',
    height: 250,
    width: '100%',
    backgroundColor: '#DB9F36',
    left: 0,
    right: 0,
    marginLeft: 'auto',
    marginRight: 'auto',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  profileContainer: {
    marginTop: 52,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  profileInfo: {
    width: 350,
    height: 130,
    top: 10,
  },
  profileImage: {
    position: 'absolute',
    width: 95,
    height: 95,
    left: 22,
    marginTop: 10,
    borderColor: '#FFFFFF',
    borderWidth: 4,
    borderRadius: 103 / 2,
    shadowColor: '#656565',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.15,
    shadowRadius: 20,
  },
  username: {
    position: 'absolute',
    width: 220,
    height: 24,
    left: 140,
    top: 30,
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 20,
    lineHeight: 24,
    color: '#000000',
  },
  bio: {
    position: 'absolute',
    width: 197,
    height: 32,
    left: 140,
    top: 60,
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 13,
    lineHeight: 16,
    color: '#000000',
  },
  containerStats: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 23,
    width: 320,
    marginTop: 5,
  },
  item: {
    marginHorizontal: 'auto',
    width: 106.67,
    height: 56,
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 14,
    lineHeight: 17,
    display: 'flex',
    alignItems: 'center',
    textAlign: 'center',
    color: '#000000',
    textShadowColor: 'rgba(8, 15, 52, 0.04)',
    textShadowOffset: {width: 0, height: 5},
    textShadowRadius: 14,
    flex: 1,
  },
  text: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 14,
    lineHeight: 17,
    display: 'flex',
    alignItems: 'center',
    textAlign: 'center',
    color: '#000000',
  },
  number: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 14,
    lineHeight: 17,
    display: 'flex',
    alignItems: 'center',
    textAlign: 'center',
    color: '#000000',
  },
  textAmigo: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 14,
    lineHeight: 17,
    display: 'flex',
    alignItems: 'center',
    textAlign: 'center',
    color: colors.aratuRed,
  },
  numberAmigo: {
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 14,
    lineHeight: 17,
    display: 'flex',
    alignItems: 'center',
    textAlign: 'center',
    color: colors.aratuRed,
  },
  segmentedControlStructure: {
    height: 50,
    width: '90%',
    marginHorizontal: 9,
    marginTop: '7%',
    backgroundColor: colors.aratuLightGray,
    borderRadius: 100,
    flexDirection: 'row',
  },
  segmentedControlLeft: {
    flex: 1,
    backgroundColor: colors.aratuLightGray,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center', // Center text vertically
  },
  segmentedControlRight: {
    flex: 1,
    backgroundColor: colors.aratuLightGray,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center', // Center text vertically
  },
  segmentedControlSelected: {
    flex: 1,
    backgroundColor: colors.aratuWhite,
    borderWidth: 1,
    borderColor: '#E8E8E8',
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center', // Center text vertically
  },
  buttonControlText: {
    fontFamily: 'Inter',
    fontWeight: '500',
    fontSize: 16,
    lineHeight: 19,
    color: colors.aratuGray,
  },
  buttonControlTextSelected: {
    fontFamily: 'Inter',
    fontWeight: '800',
    fontSize: 16,
    lineHeight: 19,
    color: colors.aratuRed,
  },
  friendFollowButton: {
    height: '5%',
    width: '60%',
    marginHorizontal: 9,
    marginTop: '7%',
    borderRadius: 100,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  friendFollowButtonText: {
    fontFamily: 'Inter',
    fontWeight: '500',
    fontSize: 16,
    lineHeight: 19,
    color: colors.aratuWhite,
  },
});

export default styles;